categories:
  - title: "⚠ Breaking Changes"
    labels:
      - "breaking-change"
  - title: "⬆️ Dependencies"
    collapse-after: 1
    labels:
      - "dependencies"
template: |
  ## What's Changed

  $CHANGES

  ---
  You like my work?

  <a href="https://www.buymeacoffee.com/mib1185" target="_blank"><img src="https://cdn.buymeacoffee.com/buttons/v2/default-yellow.png" alt="Buy Me A Coffee" height="41" width="174"></a>
