# This workflow will install Python dependencies, run tests and lint
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4.1.0

      - name: Set up Python 3.9
        uses: actions/setup-python@v4.7.0
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install -r requirements_dev.txt -e .

      - name: Run pre-commit
        run: |
          pre-commit run --all-files --show-diff-on-failure

  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4.1.0

      - name: Set up Python 3.9
        uses: actions/setup-python@v4.7.0
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install -r requirements_dev.txt -e .

      - name: Run tests
        run: |
          pytest tests --cov=aiopegelonline --cov-report=xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
